[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
upload_port = COM24

lib_deps =
    olikraus/U8g2@^2.36.18

build_flags =
    -O2
    -DARDUINO
